### ISSUE TITLE
enhancement: add context dictionary in workflow.py that stores each agent's output

### ISSUE THREAD

**Issue by george-lhj** [AI4quantum/maestro#526]
In certain use cases, a user might want to access the output of an agent from a previous step during execution. Currently, there is no built-in way to reference prior step outputs unless we explicitly wire inputs for each step.

Proposal
Add a context dictionary to the workflow execution runtime, which automatically accumulates the outputs of each agent step as the workflow progresses. This context object should be passed into each agent’s run() function, making prior outputs accessible inside agents.

Example Behavior:

When agent A finishes: ```context["A"] = agentA_output```
When agent B runs, it automatically receives: ```run(*args, context=context)```

Enables agents to optionally reference prior results without having to modify workflow YAML files extensively;uUseful for code agents, conditional branching, and intermediate debugging

**Comment by akihikokuroda** [comment]
Passing the result of previously executed steps seems good but It may cause giving unnecessary information to agents.  It may need a way to specify which output is passed to the agent.  The workflow.py has the dictionary now so the step can access to it.  So we can pass it to the agent but I want to pass only the necessary part of it.

**Comment by george-lhj** [comment]
i think this is the input wiring in workflow.py?

```
if definition.get("inputs"):
    args = []
    for inp in definition["inputs"]:
        src = inp["from"]
        if src == "prompt":
            args.append(initial_prompt)
        elif src in step_results:
            args.append(step_results[src])
        else:
            args.append(src)
```

allows you to wire any previous step directly via inputs, but not agents

**Comment by akihikokuroda** [comment]
I was wrong.  The `step` doesn't have access to the dictionary now.  It must be  passed to step.run method.

**Comment by psschwei** [comment]
Seems like [this](https://github.com/AI4quantum/maestro/blob/main/demos/workflows/cbom.ai/workflow.yaml) is an example of how to use inputs from a previous step: 

```yaml
steps:
    - name: step2
      agent: selector agent
    - name: step2_score
      agent: score
      inputs: 
        - from: "Get a java file from the github mastercard repo and return its raw link."
        - from: step2
```

For a typical agent, I'd assume the return value for `step2` is just whatever the agent returns... is that the same for a code agent? And would we need to explicitly have the code block return something to get registered as the output from the previous step?

(would be nice to add this info to the user guide)

**Comment by akihikokuroda** [comment]
> Enables agents to optionally reference prior results without having to modify workflow YAML files **extensively**
How about change the `context` in the workflow schema a little if it is not used now?

```
    steps:
      - name: step1
        agent: weather
      - name: step2
        agent: in-or-out
      - name: step3
        agent: something
      - name: step4
        agent: activity
        context:
          - from: step1
             as: weather 
          - from: step2
             as: preferences 
```

Then the `run` method of the `agent` called with context {"weather": result of step1, "preferences": result of step2}

Here is the schema update.  I took put the literal string in the context
```
                  "context": {
                    "type": "array",
                    "description": "Optional array of literal strings or `{ from: stepName }` objects to pass as context",
                    "items": {
                        {
                          "type": "object",
                          "properties": {
                            "from": {
                              "type": "string"
                            }
                            "as": {
                              "type": "string"
                            }
                          },
                          "required": ["from"],
                          "additionalProperties": false
                        }
                      ]
                    }
                  }
```
WDYT?
